
&nbsp;[系统消息] - admin进入会议室  
&nbsp;<b><a href=javascript:sayTo('admin');>admin</a></b>&nbsp;说：&nbsp;<font color=#000000>dadafad</font>&nbsp;<font color=#888888>[2011-11-21 17:23:49]</font>  
&nbsp;<b><a href=javascript:sayTo('admin');>admin</a></b>&nbsp;说：&nbsp;<font color=#000000>afdadfa</font>&nbsp;<font color=#888888>[2011-11-21 17:23:52]</font>  
&nbsp;[系统消息] - jl进入会议室  
&nbsp;<b><a href=javascript:sayTo('jl');>jl</a></b>&nbsp;说：&nbsp;<font color=#000000>fasdasfdas</font>&nbsp;<font color=#888888>[2011-11-21 17:24:59]</font>  
&nbsp;<b><a href=javascript:sayTo('jl');>jl</a></b>&nbsp;说：&nbsp;<font color=#000000>dfasdfsa</font>&nbsp;<font color=#888888>[2011-11-21 17:25:07]</font>  
&nbsp;<b><a href=javascript:sayTo('jl');>jl</a></b>&nbsp;说：&nbsp;<font color=#000000>afda</font>&nbsp;<font color=#888888>[2011-11-21 17:25:09]</font>  
&nbsp;[系统消息] - jl进入会议室  
&nbsp;<b><a href=javascript:sayTo('jl');>jl</a></b>&nbsp;说：&nbsp;<font color=#000000>fdasfdas</font>&nbsp;<font color=#888888>[2011-11-21 17:25:18]</font>  
&nbsp;<b><a href=javascript:sayTo('jl');>jl</a></b>&nbsp;说：&nbsp;<font color=#000000>fdafda</font>&nbsp;<font color=#888888>[2011-11-21 17:26:51]</font>  