ALTER TABLE flow_process ADD COLUMN AUTO_SELECT_ROLE VARCHAR(45) ;
ALTER TABLE email_body MODIFY COLUMN COMPRESS_CONTENT MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE flow_print_tpl MODIFY COLUMN CONTENT MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;

ALTER TABLE flow_process ADD COLUMN DOC_CREATE VARCHAR(45) ,
 ADD COLUMN DOC_ATTACH_PRIV VARCHAR(45) NOT NULL ;
 
ALTER TABLE doc_flow_process ADD COLUMN AUTO_SELECT_ROLE VARCHAR(45) ;
ALTER TABLE doc_flow_print_tpl MODIFY COLUMN CONTENT MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;

ALTER TABLE doc_flow_process ADD COLUMN DOC_CREATE VARCHAR(45) ,
 ADD COLUMN DOC_ATTACH_PRIV VARCHAR(45) NOT NULL ; 
 ALTER TABLE doc_flow_process ADD COLUMN DOC_SMS_STYLE TEXT;