-- email 头信息表
create table EMAIL(
  SEQ_ID int primary key ,
  TO_ID int not null ,
  READ_FLAG CHAR(1) DEFAULT '' NOT NULL,
  DELETE_FLAG CHAR(1) DEFAULT '' NOT NULL,
  BOX_ID INT DEFAULT 0 NOT NULL,
  BODY_ID INT DEFAULT 0 NOT NULL,
  RECEIPT CHAR(1) DEFAULT 0 NOT NULL
);
exec pr_createidentitycolumn('EMAIL','SEQ_ID');
-- email_body 正文信息表
create table EMAIL_BODY(
  SEQ_ID INT PRIMARY KEY ,
  FROM_ID INT NOT NULL,
  TO_ID VARCHAR2(4000) NOT NULL,
  COPY_TO_ID VARCHAR2(4000) ,
  SECRET_TO_ID VARCHAR2(4000),
  SUBJECT VARCHAR2(200),
  CONTENT CLOB NOT NULL,
  SEND_TIME timestamp not null,
  ATTACHMENT_ID VARCHAR2(4000),
  ATTACHMENT_NAME VARCHAR2(4000),
  SEND_FLAG CHAR(1) DEFAULT 0 NOT NULL,
  SMS_REMIND CHAR(1) DEFAULT 0 NOT NULL,
  IMPORTANT VARCHAR(10) DEFAULT '0' NOT NULL,
  ENSIZE number(38),
  FROM_WEBMAIL VARCHAR(200),
  TO_WEBMAIL VARCHAR2(4000),
  COMPRESS_CONTENT BLOB 
);
exec pr_createidentitycolumn('EMAIL_BODY','SEQ_ID');
create table EMAIL_BOX(
  SEQ_ID INT PRIMARY KEY,
  BOX_NO INT DEFAULT 0 NOT NULL,
  BOX_NAME VARCHAR2(200) NOT NULL,
  USER_ID INT NOT NULL,
  DEFAULT_COUNT NUMBER(5) DEFAULT 10
);
exec pr_createidentitycolumn('EMAIL_BOX','SEQ_ID');
